version: "3.9"

services:

  db:
    image: mysql
    container_name: db
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/init.sql:/data/application/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local